# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2

before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "btptf_v{{ .Version }}"
archives:
  - formats: ["binary"]
    name_template: "btptf_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  algorithm: sha256
  split: true
changelog:
  use: github-native
binary_signs:
  - artifacts: binary
    signature: "{{ .ArtifactPath }}.sig"
    args:
      - --batch
      - --yes
      - --armor
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "{{ .ArtifactPath }}.sig"
      - --detach-sign
      - "{{ .ArtifactPath }}"
nfpms:
  - id: btptf
    # Name of the package - Default: ProjectName.

    # File name of the package.
    # Default: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'.

    # Your app's vendor.
    vendor: SAP SE

    # Your app's homepage.
    #
    # Default: inferred from global metadata.
    homepage: https://github.com/SAP/terraform-exporter-btp

    # Your app's description.
    #
    # Default: inferred from global metadata.
    description: |-
      The Terraform Exporter for SAP BTP is a tool that helps export resources in a BTP Global Account.
      It generates Terraform scripts for the resources and import those resources into a Terraform state file.

    # Your app's license.
    #
    # Default: inferred from global metadata.
    license: Apache 2.0

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Packages your package recommends installing. (overridable)
    recommends:
      - terraform

    # Path that the binaries should be installed.
    #
    # Default: '/usr/bin'.

    # Section.
    section: default

    # Priority.
    priority: normal

    # Makes a meta package - an empty package that contains only supporting
    # files and dependencies.
    # When set to `true`, the `builds` option is ignored.
    meta: false

    maintainer: "See GitHub <https://github.com/SAP/terraform-exporter-btp>"
